import type {
  ProjectSettings,
  TaxSettings,
  ItemSettings,
  ContactSettings,
  SalesSettings,
  CashierSettings,
  PurchaseSettings,
  PaymentSettings,
  StockAlertSettings,
  SystemSettings,
  ShortcutSettings,
  EmailSettings,
  SmsSettings,
  RewardSettings,
  ExtraUnitSettings,
  CustomLabelSettings,
  PharmacySettings,
} from "./types"

export const DEFAULT_PROJECT_SETTINGS: ProjectSettings = {
  name: "",
  legalName: "",
  ownerName: "",
  ownerTitle: "صيدلي",
  address: "",
  phone: "",
  mobile: "",
  email: "",
  website: "",
  logo: null,
  taxId: "",
  commercialRegister: "",
  healthLicense: "",
  currency: "EGP",
  currencySymbol: "ج.م",
  currencySymbolPlacement: "before",
  timezone: "Africa/Cairo",
  language: "ar",
  dateFormat: "YYYY-MM-DD",
  timeFormat: "24",
  country: "مصر",
  city: "",
  district: "",
  building: "",
  floor: "",
  landmark: "",
  facebook: "",
  twitter: "",
  instagram: "",
  whatsapp: "",
  notes: "",
}

export const DEFAULT_TAX_SETTINGS: TaxSettings = {
  defaultTaxRate: 0,
  taxCalculationMethod: "exclusive",
  taxNumber: "",
  taxAuthority: "",
  vatRate: 0,
  includeTaxInPrice: false,
  applyTaxToShipping: false,
  taxRounding: "nearest",
  taxOnDiscount: false,
  enableMultipleTaxes: false,
  taxDisplayLabel: "ضريبة القيمة المضافة",
}

export const DEFAULT_ITEM_SETTINGS: ItemSettings = {
  defaultUnit: "قطعة",
  enableExpiryTracking: true,
  enableBatchTracking: false,
  enableSerialTracking: false,
  enableBarcodeScanning: true,
  defaultPurchasePrice: 0,
  defaultSellingPrice: 0,
  defaultMinStock: 0,
  defaultMaxStock: 0,
  defaultReorderPoint: 0,
  autoGenerateBarcode: false,
  barcodePrefix: "",
  barcodeSymbology: "Code-128",
  costingMethod: "average",
  allowNegativeStock: false,
  enablePriceGroups: false,
  enableWholesalePrice: true,
  enableMultiUnit: false,
  itemNameFormat: "arabic",
  showExpiryInSales: true,
  showBatchInSales: false,
  daysToExpiryWarning: 30,
}

export const DEFAULT_CONTACT_SETTINGS: ContactSettings = {
  defaultCustomerGroup: "",
  defaultSupplierGroup: "",
  defaultPaymentTerm: "cash",
  enableCustomerCreditLimit: false,
  defaultCreditLimit: 0,
  enableCustomerLoyalty: true,
  customerDisplayName: "name",
  requirePhoneForCustomers: false,
  requirePhoneForSuppliers: false,
  enableCustomerPriceGroup: false,
  autoCreateCustomer: false,
  defaultCustomerId: "",
  enableCustomerDiscount: false,
  defaultCustomerDiscount: 0,
}

export const DEFAULT_SALES_SETTINGS: SalesSettings = {
  invoicePrefix: "INV-",
  invoiceSuffix: "",
  nextInvoiceNumber: 1,
  receiptFooter: "شكراً لتعاملكم معنا",
  receiptHeader: "",
  saleItemBehavior: "increase",
  defaultDiscountPercent: 0,
  maxDiscountPercent: 100,
  enableDiscount: true,
  enableReturn: true,
  returnWindowDays: 30,
  requireReturnReason: true,
  enableSalesRep: false,
  salesRepCommissionBase: "invoice",
  salesRepCommissionRate: 0,
  enablePriceOverride: true,
  requirePriceOverrideReason: false,
  defaultSaleStatus: "invoice",
  enableDraftInvoices: true,
  enablePriceOffers: true,
  priceOfferValidDays: 7,
  enableShipping: false,
  defaultShippingCost: 0,
  enableFreeReturns: false,
}

export const DEFAULT_CASHIER_SETTINGS: CashierSettings = {
  posLayout: "grid",
  posColumns: 4,
  enableQuickKeys: true,
  quickKeys: [],
  enableCashDrawer: false,
  cashDrawerPort: "",
  autoOpenDrawer: true,
  enableCustomerSelection: true,
  enableSearch: true,
  searchMinChars: 2,
  showItemImage: true,
  showItemStock: true,
  showItemPrice: true,
  enableCategoryFilter: true,
  enableBarcodeSearch: true,
  enableCalculator: true,
  holdSaleEnabled: true,
  quickSaleEnabled: true,
  cashCategoryScope: "pos",
  defaultCashCategory: "",
  enableSounds: true,
  soundVolume: 55,
  audioOnScan: true,
}

export const DEFAULT_PURCHASE_SETTINGS: PurchaseSettings = {
  orderPrefix: "PO-",
  nextOrderNumber: 1,
  enablePurchaseApproval: false,
  requireApprovalAbove: 10000,
  defaultOrderStatus: "pending",
  enablePartialReceiving: true,
  enablePurchaseReturn: true,
  returnWindowDays: 14,
  enableShippingCost: true,
  defaultShippingCost: 0,
  enablePurchaseDiscount: true,
  defaultDiscountPercent: 0,
  autoCreateStockOnReceive: true,
  enableBatchTracking: false,
  enableExpiryTracking: true,
}

export const DEFAULT_PAYMENT_SETTINGS: PaymentSettings = {
  defaultPaymentMethod: "cash",
  acceptedPaymentMethods: ["cash", "card"],
  enableCardPayment: true,
  cardFeePercent: 0,
  enableWalletPayment: true,
  enableBankTransfer: true,
  enablePartialPayment: true,
  enableChangeCalculation: true,
  paymentRounding: 0.05,
  defaultPaymentTerm: "cash",
  enableDeposit: false,
  depositPercent: 0,
}

export const DEFAULT_STOCK_ALERT_SETTINGS: StockAlertSettings = {
  enableLowStockAlerts: true,
  lowStockThreshold: 10,
  enableExpiryAlerts: true,
  expiryWarningDays: 30,
  enableOutOfStockAlerts: true,
  alertConditions: ["below_min", "expiring_soon"],
  defaultSeverity: "medium",
  alertFrequency: "daily",
  enableEmailAlerts: false,
  enableInAppAlerts: true,
  enableSmsAlerts: false,
  maxAlertItems: 50,
}

export const DEFAULT_SYSTEM_SETTINGS: SystemSettings = {
  appName: "Logixa Pharmacy",
  appVersion: "1.0.0",
  companyName: "",
  supportPhone: "",
  supportEmail: "",
  enableAutoBackup: true,
  backupFrequency: "daily",
  backupRetentionDays: 30,
  backupLocation: "",
  enableAuditLog: true,
  auditLogRetentionDays: 90,
  enableMultiBranch: false,
  enableMultiCurrency: false,
  defaultBranchId: "",
  enableDarkMode: false,
  enableNotifications: true,
  sessionTimeout: 60,
  maxLoginAttempts: 5,
  enableTwoFactor: false,
  maintenanceMode: false,
}

export const DEFAULT_SHORTCUT_SETTINGS: ShortcutSettings = {
  enableShortcuts: true,
  shortcuts: {
    "ctrl+n": "new-item",
    "ctrl+s": "save",
    "ctrl+f": "search",
    "ctrl+p": "print",
    "ctrl+d": "duplicate",
    "f1": "help",
    "f8": "cashier",
    "escape": "close",
  },
}

export const DEFAULT_EMAIL_SETTINGS: EmailSettings = {
  smtpHost: "",
  smtpPort: 587,
  smtpUsername: "",
  smtpPassword: "",
  smtpEncryption: "tls",
  fromAddress: "",
  fromName: "",
  enableEmailNotifications: false,
  emailSignature: "",
}

export const DEFAULT_SMS_SETTINGS: SmsSettings = {
  provider: "",
  apiKey: "",
  apiSecret: "",
  senderId: "",
  enableSmsNotifications: false,
  smsSignature: "",
  defaultCountryCode: "+20",
}

export const DEFAULT_REWARD_SETTINGS: RewardSettings = {
  enableRewards: false,
  pointsPerAmount: 100,
  pointsCurrency: "EGP",
  pointsPerPurchase: 1,
  redeemRate: 1,
  minRedeemPoints: 100,
  maxRedeemPercent: 50,
  expiryDays: 365,
  enableBirthdayReward: true,
  birthdayRewardPoints: 100,
  enableSignupReward: true,
  signupRewardPoints: 50,
  rewardTiers: ["برونزي", "فضي", "ذهبي", "بلاتيني"],
}

export const DEFAULT_EXTRA_UNIT_SETTINGS: ExtraUnitSettings = {
  enableExtraUnits: false,
  units: ["علبة", "شريط", "قرص", "كابسولة", "أمبول", "زجاجة", "بخاخ", "أنبوب", "قطارة", "عبوة"],
}

export const DEFAULT_CUSTOM_LABEL_SETTINGS: CustomLabelSettings = {
  enableCustomLabels: false,
  itemFields: [],
  purchaseFields: [],
  shippingFields: [],
  saleFields: [],
  paymentFields: [],
  contactFields: [],
  locationFields: [],
  userFields: [],
  serviceFields: [],
}

export const DEFAULT_PHARMACY_SETTINGS: PharmacySettings = {
  project: DEFAULT_PROJECT_SETTINGS,
  tax: DEFAULT_TAX_SETTINGS,
  items: DEFAULT_ITEM_SETTINGS,
  contacts: DEFAULT_CONTACT_SETTINGS,
  sales: DEFAULT_SALES_SETTINGS,
  cashier: DEFAULT_CASHIER_SETTINGS,
  purchases: DEFAULT_PURCHASE_SETTINGS,
  payments: DEFAULT_PAYMENT_SETTINGS,
  stockAlerts: DEFAULT_STOCK_ALERT_SETTINGS,
  system: DEFAULT_SYSTEM_SETTINGS,
  shortcuts: DEFAULT_SHORTCUT_SETTINGS,
  email: DEFAULT_EMAIL_SETTINGS,
  sms: DEFAULT_SMS_SETTINGS,
  rewards: DEFAULT_REWARD_SETTINGS,
  extraUnits: DEFAULT_EXTRA_UNIT_SETTINGS,
  customLabels: DEFAULT_CUSTOM_LABEL_SETTINGS,
}
